import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { HelpAssistant } from "./HelpAssistant";
import { AuthContext, type AuthState } from "../../stores/auth-store";

const ask = vi.fn();
vi.mock("../../api/help-api", () => ({ askApplicationHelp: (...args: unknown[]) => ask(...args) }));
const auth = { organizationId:"O", user:{id:"U",organization_id:"O",email:"admin@example.com",full_name:"Admin",role:"organization_admin",is_active:true}, session:null,isAuthenticated:true,isInitializing:false,login:vi.fn(),logout:vi.fn() } satisfies AuthState;
const response = { answer:"Open Workspaces and create an isolated area.", steps:["Open Workspaces.","Select Create Workspace."], related_pages:["Workspace Setup"], warnings:[], links:["Workspace Setup"] };
function widget(path="/app/workspaces", value=auth) { return render(<AuthContext.Provider value={value}><MemoryRouter initialEntries={[path]}><HelpAssistant/></MemoryRouter></AuthContext.Provider>); }

describe("HelpAssistant", () => {
  beforeEach(() => { vi.clearAllMocks(); localStorage.clear(); ask.mockResolvedValue(response); });
  it("opens, minimizes, expands, closes, and restores focus", () => { widget(); const launcher=screen.getByRole("button",{name:"Open application help"}); fireEvent.click(launcher); expect(screen.getByRole("complementary",{name:"Application Help"})).toBeInTheDocument(); fireEvent.click(screen.getByRole("button",{name:"Expand application help"})); expect(screen.getByRole("dialog",{name:"Application Help"})).toBeInTheDocument(); fireEvent.keyDown(document,{key:"Escape"}); expect(screen.getByRole("button",{name:"Open application help"})).toHaveFocus(); });
  it("uses route-aware approved quick questions", () => { widget("/app/connections"); fireEvent.click(screen.getByRole("button",{name:"Open application help"})); expect(screen.getByRole("button",{name:"How do I connect a database?"})).toBeInTheDocument(); });
  it("submits a quick question and renders structured approved guidance", async () => { widget(); fireEvent.click(screen.getByRole("button",{name:"Open application help"})); fireEvent.click(screen.getByRole("button",{name:"How do I create a workspace?"})); expect(screen.getByRole("status")).toHaveTextContent("approved guidance"); expect(await screen.findByText("Open Workspaces and create an isolated area.")).toBeInTheDocument(); expect(screen.getByText("Select Create Workspace.")).toBeInTheDocument(); expect(ask).toHaveBeenCalledWith("How do I create a workspace?","/app/workspaces",expect.any(AbortSignal)); });
  it("sends on Enter, permits Shift+Enter, and blocks empty input", async () => { widget(); fireEvent.click(screen.getByRole("button",{name:"Open application help"})); const input=screen.getByLabelText("Ask application help"); expect(screen.getByRole("button",{name:"Send help question"})).toBeDisabled(); fireEvent.change(input,{target:{value:"How do reports work?"}}); fireEvent.keyDown(input,{key:"Enter",shiftKey:true}); expect(ask).not.toHaveBeenCalled(); fireEvent.keyDown(input,{key:"Enter"}); await waitFor(()=>expect(ask).toHaveBeenCalledTimes(1)); });
  it("hides unauthorized administrative links", async () => { widget("/app/dashboard",{...auth,user:{...auth.user,role:"read_only_user"}}); fireEvent.click(screen.getByRole("button",{name:"Open application help"})); fireEvent.change(screen.getByLabelText("Ask application help"),{target:{value:"How do I add a user?"}}); fireEvent.click(screen.getByRole("button",{name:"Send help question"})); await screen.findByText(response.answer); expect(screen.queryByRole("link",{name:/Users & Access/})).not.toBeInTheDocument(); });
  it("shows retry after an API error", async () => { ask.mockRejectedValueOnce(new Error("Help unavailable")); widget(); fireEvent.click(screen.getByRole("button",{name:"Open application help"})); fireEvent.change(screen.getByLabelText("Ask application help"),{target:{value:"How do I create a workspace?"}}); fireEvent.click(screen.getByRole("button",{name:"Send help question"})); expect(await screen.findByRole("alert")).toHaveTextContent("Help unavailable"); ask.mockResolvedValue(response); fireEvent.click(screen.getByRole("button",{name:"Retry"})); await waitFor(()=>expect(ask).toHaveBeenCalledTimes(2)); });
  it("clears the conversation when the authenticated user changes", async () => { const view=widget(); fireEvent.click(screen.getByRole("button",{name:"Open application help"})); fireEvent.click(screen.getByRole("button",{name:"How do I create a workspace?"})); await screen.findByText(response.answer); view.rerender(<AuthContext.Provider value={{...auth,user:{...auth.user,id:"OTHER"}}}><MemoryRouter><HelpAssistant/></MemoryRouter></AuthContext.Provider>); expect(screen.queryByText(response.answer)).not.toBeInTheDocument(); });
});
