from __future__ import annotations

from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt, RGBColor

from legacydb_copilot.services.report_generator import InvestigationReport


def _add_table(doc: Document, title: str, columns: list[str], rows: list[dict]) -> None:
    """
    Owner: Mukesh Dabi
    Purpose:
        Internal helper for add table within docx_generator.py.
    
    Input:
        Function parameters declared in the signature.
    
    Output:
        Return value declared by the type hints or route response model.
    
    How it is called:
        Internal callers in docx_generator.py.
    
    Where it fits in the flow:
        Application orchestration -> service function -> structured result for the next workflow step.
    
    Safety considerations:
        Keep tenant/workspace boundaries and do not introduce unsafe database or secret handling.
    """
    doc.add_heading(title, level=3)
    table = doc.add_table(rows=1, cols=max(1, len(columns)))
    table.style = "Table Grid"
    header = table.rows[0].cells
    for index, column in enumerate(columns):
        header[index].text = column
    for row in rows:
        cells = table.add_row().cells
        for index, column in enumerate(columns):
            cells[index].text = str(row.get(column, ""))


def write_docx(report: InvestigationReport, output_path: Path) -> None:
    """
    Owner: Mukesh Dabi
    Purpose:
        Handles write docx within the Database Support AI application flow.
    
    Input:
        Function parameters declared in the signature.
    
    Output:
        Return value declared by the type hints or route response model.
    
    How it is called:
        Investigation, reporting, verification, or knowledge workflows as needed.
    
    Where it fits in the flow:
        Application orchestration -> service function -> structured result for the next workflow step.
    
    Safety considerations:
        Keep tenant/workspace boundaries and do not introduce unsafe database or secret handling.
    """
    doc = Document()
    section = doc.sections[0]
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.7)
    section.right_margin = Inches(0.7)

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("Database Support AI\nEnterprise Investigation Report")
    run.bold = True
    run.font.size = Pt(24)
    run.font.color.rgb = RGBColor(16, 50, 74)

    doc.add_paragraph("Company logo placeholder")
    for label, value in (
        ("Workspace", report.cover.workspace),
        ("Database", report.cover.database),
        ("Generated By", report.cover.generated_by),
        ("Generated On", report.cover.generated_on),
        ("Investigation ID", report.cover.investigation_id),
        ("Report Version", report.cover.report_version),
    ):
        p = doc.add_paragraph()
        p.add_run(f"{label}: ").bold = True
        p.add_run(str(value))

    doc.add_page_break()
    doc.add_heading("Table of Contents", level=1)
    for index, section in enumerate(report.sections, start=1):
        doc.add_paragraph(f"{index}. {section.title}")

    for index, section in enumerate(report.sections, start=1):
        doc.add_heading(f"{index}. {section.title}", level=1)
        for paragraph in section.paragraphs:
            doc.add_paragraph(str(paragraph))
        for item in section.items:
            doc.add_paragraph(str(item), style="List Bullet")
        for table in section.tables:
            _add_table(doc, table.title, table.columns, table.rows)
        for block in section.sql_blocks:
            doc.add_heading(block.purpose, level=3)
            doc.add_paragraph(f"Expected Result: {block.expected_result}")
            doc.add_paragraph(f"Risk: {block.risk}")
            sql = doc.add_paragraph()
            run = sql.add_run(block.sql)
            run.font.name = "Consolas"
            run.font.size = Pt(9)

    footer = doc.sections[0].footer.paragraphs[0]
    footer.text = f"Generated by Database Support AI | Version {report.cover.report_version} | {report.cover.investigation_id}"
    doc.save(output_path)
