from __future__ import annotations

from pathlib import Path
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    Preformatted,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from legacydb_copilot.services.report_generator import InvestigationReport, ReportSection


def _footer(canvas, doc, report: InvestigationReport) -> None:
    """
    Owner: Mukesh Dabi
    Purpose:
        Internal helper for footer within pdf_generator.py.
    
    Input:
        Function parameters declared in the signature.
    
    Output:
        Return value declared by the type hints or route response model.
    
    How it is called:
        Internal callers in pdf_generator.py.
    
    Where it fits in the flow:
        Application orchestration -> service function -> structured result for the next workflow step.
    
    Safety considerations:
        Keep tenant/workspace boundaries and do not introduce unsafe database or secret handling.
    """
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#60707c"))
    canvas.drawString(0.7 * inch, 0.45 * inch, "Generated by Database Support AI")
    canvas.drawRightString(7.8 * inch, 0.45 * inch, f"Page {doc.page} | Version {report.cover.report_version}")
    if report.confidential_watermark:
        canvas.setFont("Helvetica-Bold", 48)
        canvas.setFillColor(colors.Color(0.6, 0.1, 0.1, alpha=0.08))
        canvas.translate(4.25 * inch, 5.5 * inch)
        canvas.rotate(35)
        canvas.drawCentredString(0, 0, "CONFIDENTIAL")
    canvas.restoreState()


def _table(title: str, columns: list[str], rows: list[dict]) -> list:
    """
    Owner: Mukesh Dabi
    Purpose:
        Internal helper for table within pdf_generator.py.
    
    Input:
        Function parameters declared in the signature.
    
    Output:
        Return value declared by the type hints or route response model.
    
    How it is called:
        Internal callers in pdf_generator.py.
    
    Where it fits in the flow:
        Application orchestration -> service function -> structured result for the next workflow step.
    
    Safety considerations:
        Keep tenant/workspace boundaries and do not introduce unsafe database or secret handling.
    """
    story = [Paragraph(title, ParagraphStyle("Sub", fontName="Helvetica-Bold", fontSize=11, textColor=colors.HexColor("#0f5f8f")))]
    header_style = ParagraphStyle("TableHeader", fontName="Helvetica-Bold", fontSize=7, leading=9, wordWrap="CJK")
    cell_style = ParagraphStyle("TableCell", fontName="Helvetica", fontSize=7, leading=9, wordWrap="CJK")

    def cell(value: object, style: ParagraphStyle) -> Paragraph:
        # Paragraphs wrap table content; raw strings can create a single row
        # taller than the page and cause ReportLab's LayoutError.
        text = escape(str(value or "")).replace("\n", "<br/>")
        return Paragraph(text, style)

    data = [[cell(column, header_style) for column in columns]]
    data.extend([[cell(row.get(column, ""), cell_style) for column in columns] for row in rows])
    available_width = LETTER[0] - 72  # Matches the document's 36-point side margins.
    col_widths = [available_width / len(columns)] * len(columns) if columns else None
    tbl = Table(data, colWidths=col_widths, repeatRows=1, splitByRow=1, splitInRow=1, hAlign="LEFT")
    tbl.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8f4f3")),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cfdbe2")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 7),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fbfc")]),
            ]
        )
    )
    story.extend([tbl, Spacer(1, 10)])
    return story


def _section(section: ReportSection, styles) -> list:
    """
    Owner: Mukesh Dabi
    Purpose:
        Internal helper for section within pdf_generator.py.
    
    Input:
        Function parameters declared in the signature.
    
    Output:
        Return value declared by the type hints or route response model.
    
    How it is called:
        Internal callers in pdf_generator.py.
    
    Where it fits in the flow:
        Application orchestration -> service function -> structured result for the next workflow step.
    
    Safety considerations:
        Keep tenant/workspace boundaries and do not introduce unsafe database or secret handling.
    """
    story = [Paragraph(section.title, styles["Heading2"])]
    for paragraph in section.paragraphs:
        story.append(Paragraph(str(paragraph), styles["BodyText"]))
    for item in section.items:
        story.append(Paragraph(f"✓ {item}", styles["BodyText"]))
    for table in section.tables:
        story.extend(_table(table.title, table.columns, table.rows))
    for block in section.sql_blocks:
        story.append(Paragraph(block.purpose, styles["Heading3"]))
        story.append(Paragraph(f"Expected Result: {block.expected_result}", styles["BodyText"]))
        story.append(Paragraph(f"Risk: {block.risk}", styles["BodyText"]))
        story.append(Preformatted(block.sql, styles["SqlCode"]))
    story.append(Spacer(1, 12))
    return story


def write_pdf(report: InvestigationReport, output_path: Path) -> None:
    """
    Owner: Mukesh Dabi
    Purpose:
        Handles write pdf within the Database Support AI application flow.
    
    Input:
        Function parameters declared in the signature.
    
    Output:
        Return value declared by the type hints or route response model.
    
    How it is called:
        Investigation, reporting, verification, or knowledge workflows as needed.
    
    Where it fits in the flow:
        Application orchestration -> service function -> structured result for the next workflow step.
    
    Safety considerations:
        Keep tenant/workspace boundaries and do not introduce unsafe database or secret handling.
    """
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle("SqlCode", fontName="Courier", fontSize=7, leading=9, backColor=colors.HexColor("#f3f7f9"), borderColor=colors.HexColor("#0f8f86"), borderWidth=0.5, borderPadding=6))
    styles["Heading1"].textColor = colors.HexColor("#10324a")
    styles["Heading2"].backColor = colors.HexColor("#10324a")
    styles["Heading2"].textColor = colors.white
    styles["Heading2"].borderPadding = 7
    is_executive = report.cover.title.startswith("Executive RCA Report")
    doc = SimpleDocTemplate(str(output_path), pagesize=LETTER, rightMargin=36, leftMargin=36, topMargin=42, bottomMargin=42)
    story = [
        Paragraph("Database Support AI", styles["Title"]),
        Paragraph("Executive RCA Report" if is_executive else "Enterprise Investigation Report", styles["Title"]),
        Spacer(1, 12 if is_executive else 24),
        Paragraph(f"Workspace: {report.cover.workspace}", styles["BodyText"]),
        Paragraph(f"Database: {report.cover.database}", styles["BodyText"]),
        Paragraph(f"Generated By: {report.cover.generated_by}", styles["BodyText"]),
        Paragraph(f"Generated On: {report.cover.generated_on}", styles["BodyText"]),
        Paragraph(f"Investigation ID: {report.cover.investigation_id}", styles["BodyText"]),
        Paragraph(f"Report Version: {report.cover.report_version}", styles["BodyText"]),
    ]
    if is_executive:
        story.append(Spacer(1, 14))
    else:
        story.extend([PageBreak(), Paragraph("Table of Contents", styles["Heading1"])])
        for index, section in enumerate(report.sections, start=1):
            story.append(Paragraph(f"{index}. {section.title}", styles["BodyText"]))
        story.append(PageBreak())
    for section in report.sections:
        story.extend(_section(section, styles))
    doc.build(story, onFirstPage=lambda c, d: _footer(c, d, report), onLaterPages=lambda c, d: _footer(c, d, report))
