from enum import StrEnum


class EntityResolutionStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    RESOLVED = "RESOLVED"
    AMBIGUOUS = "AMBIGUOUS"
    NOT_FOUND = "NOT_FOUND"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"


class CoverageStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    PARTIAL = "PARTIAL"
    COMPLETE = "COMPLETE"
    BLOCKED = "BLOCKED"
    LIMIT_REACHED = "LIMIT_REACHED"


class WorkflowReproductionStatus(StrEnum):
    NOT_ASSESSED = "NOT_ASSESSED"
    REPRODUCED = "REPRODUCED"
    NOT_REPRODUCED = "NOT_REPRODUCED"
    INCOMPLETE = "INCOMPLETE"
    BLOCKED = "BLOCKED"


class WorkflowReasoningMode(StrEnum):
    NOT_DECIDED = "NOT_DECIDED"
    NORMAL_ROOT_CAUSE = "NORMAL_ROOT_CAUSE"
    EVIDENCE_SUMMARY_NOT_REPRODUCED = "EVIDENCE_SUMMARY_NOT_REPRODUCED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    NO_VERIFIED_EVIDENCE = "NO_VERIFIED_EVIDENCE"
    NEEDS_HUMAN_REVIEW = "NEEDS_HUMAN_REVIEW"
    SKIP = "SKIP"


class WorkflowTerminalStatus(StrEnum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    COMPLETED_NOT_REPRODUCED = "COMPLETED_NOT_REPRODUCED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    PARTIAL_LIMIT_REACHED = "PARTIAL_LIMIT_REACHED"
    ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
    AMBIGUOUS_ENTITY = "AMBIGUOUS_ENTITY"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"
    NEEDS_REVIEW = "NEEDS_REVIEW"


class ObjectDisposition(StrEnum):
    REQUIRED = "REQUIRED"
    OPTIONAL = "OPTIONAL"
    PLANNED = "PLANNED"
    INSPECTED = "INSPECTED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    INACCESSIBLE = "INACCESSIBLE"


class RelationshipVerification(StrEnum):
    VERIFIED = "VERIFIED"
    INFERRED = "INFERRED"


class QueryValidationStatus(StrEnum):
    NOT_VALIDATED = "NOT_VALIDATED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class QueryExecutionStatus(StrEnum):
    NOT_EXECUTED = "NOT_EXECUTED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"
    BLOCKED = "BLOCKED"


class EvidenceOutcome(StrEnum):
    POSITIVE_ROWS = "POSITIVE_ROWS"
    NO_MATCHING_ROW = "NO_MATCHING_ROW"
    NULL_VALUE = "NULL_VALUE"
    REQUIRED_VALUE_MISSING = "REQUIRED_VALUE_MISSING"
    OPTIONAL_NULL = "OPTIONAL_NULL"
    MISSING_RELATIONSHIP = "MISSING_RELATIONSHIP"
