IF DB_ID(N'EvalPayroll') IS NULL CREATE DATABASE [EvalPayroll];
IF DB_ID(N'EvalClinic') IS NULL CREATE DATABASE [EvalClinic];
IF DB_ID(N'EvalOrders') IS NULL CREATE DATABASE [EvalOrders];
IF DB_ID(N'EvalBanking') IS NULL CREATE DATABASE [EvalBanking];
IF DB_ID(N'EvalShipping') IS NULL CREATE DATABASE [EvalShipping];
IF SUSER_ID(N'evaladmin') IS NULL CREATE LOGIN [evaladmin] WITH PASSWORD=N'A9!n6iYuqAwQt3JBfTkwDSTd167Y6hAQ1pJ', CHECK_POLICY=OFF;
IF SUSER_ID(N'evalreader') IS NULL CREATE LOGIN [evalreader] WITH PASSWORD=N'A9!n6iYuqAwQt3JBfTkwDSTd167Y6hAQ1pJ', CHECK_POLICY=OFF;
