import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { assignWorkspaceMember, createManagedUser, deactivateWorkspaceMember, listManagedUsers, listWorkspaceMembers, updateManagedUser } from "../../api/access-api";
import { listWorkspaces } from "../../api/workspace-api";
import { Alert, Card, EmptyState, FormField, PageHeader, PrimaryButton, SecondaryButton, Select, SkeletonLoader, humanize } from "../../components/ui";
import { useAuth } from "../../hooks/use-auth";
import type { ManagedUser, OrganizationRole, WorkspaceMembership, WorkspaceRole } from "../../models/access";
import type { Workspace } from "../../models/workspace";

const roles: OrganizationRole[] = ["organization_admin", "developer", "dba", "support_engineer", "read_only_user", "auditor"];
const workspaceRoles: WorkspaceRole[] = ["OWNER", "ADMIN", "DBA", "DEVELOPER", "VIEWER", "AUDITOR"];
const blankForm = { full_name: "", email: "", password: "", role: "read_only_user" as OrganizationRole };
const errorMessage = (value: unknown) => value instanceof Error ? value.message : "The access request failed.";
const initials = (user: ManagedUser) => (user.full_name || user.email).split(/\s+|@/).filter(Boolean).slice(0, 2).map(part => part[0]?.toUpperCase()).join("");

function SummaryCard({ icon, value, label, detail }: { icon: string; value: number; label: string; detail: string }) {
  return <Card className="access-summary-card"><span className="access-summary-icon" aria-hidden="true">{icon}</span><strong>{value}</strong><div><b>{label}</b><small>{detail}</small></div></Card>;
}

function AccessDialog({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) {
  const closeRef = useRef<HTMLButtonElement>(null); const dialogRef = useRef<HTMLElement>(null);
  useEffect(() => { closeRef.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); if (event.key === "Tab") { const focusable = [...(dialogRef.current?.querySelectorAll<HTMLElement>("button:not(:disabled), select:not(:disabled), input:not(:disabled), [href]") || [])]; if (!focusable.length) return; const first = focusable[0], last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } }; document.addEventListener("keydown", key); return () => document.removeEventListener("keydown", key); }, [onClose]);
  return <div className="access-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><section ref={dialogRef} className="access-modal" role="dialog" aria-modal="true" aria-labelledby="access-dialog-title"><header><h2 id="access-dialog-title">{title}</h2><button ref={closeRef} className="icon-button" aria-label="Close dialog" onClick={onClose}>×</button></header>{children}</section></div>;
}

export function UsersAccessPage() {
  const { organizationId, user: actor } = useAuth();
  const authorized = actor?.role === "super_admin" || actor?.role === "organization_admin";
  const [users, setUsers] = useState<ManagedUser[]>([]); const [workspaces, setWorkspaces] = useState<Workspace[]>([]); const [memberships, setMemberships] = useState<WorkspaceMembership[]>([]);
  const [search, setSearch] = useState(""); const [roleFilter, setRoleFilter] = useState(""); const [statusFilter, setStatusFilter] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [formErrors, setFormErrors] = useState<Record<string, string>>({});
  const [form, setForm] = useState(blankForm); const [workspaceId, setWorkspaceId] = useState(""); const [workspaceRole, setWorkspaceRole] = useState<WorkspaceRole>("VIEWER"); const [showPassword, setShowPassword] = useState(false);
  const [selected, setSelected] = useState<ManagedUser | null>(null); const [confirmTarget, setConfirmTarget] = useState<ManagedUser | null>(null); const [addWorkspaceId, setAddWorkspaceId] = useState(""); const [addWorkspaceRole, setAddWorkspaceRole] = useState<WorkspaceRole>("VIEWER");

  const load = useCallback(async (signal?: AbortSignal) => { if (!organizationId || !authorized) { setLoading(false); return; } setLoading(true); setError(null); try { const [nextUsers, nextWorkspaces] = await Promise.all([listManagedUsers(organizationId, signal), listWorkspaces(organizationId, signal)]); const groups = await Promise.all(nextWorkspaces.map(w => listWorkspaceMembers(w.id, signal))); setUsers(nextUsers); setWorkspaces(nextWorkspaces); setMemberships(groups.flat()); } catch (cause) { if ((cause as { name?: string }).name !== "AbortError") setError(errorMessage(cause)); } finally { if (!signal?.aborted) setLoading(false); } }, [organizationId, authorized]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  const filtered = useMemo(() => users.filter(user => { const text = `${user.full_name} ${user.email} ${user.role}`.toLowerCase(); return text.includes(search.trim().toLowerCase()) && (!roleFilter || user.role === roleFilter) && (!statusFilter || String(user.is_active) === statusFilter); }), [users, search, roleFilter, statusFilter]);
  const membershipFor = (userId: string) => memberships.filter(item => item.user_id === userId && item.is_active);
  function validate() { const next: Record<string, string> = {}; if (!form.full_name.trim()) next.full_name = "Full name is required."; if (!/^\S+@\S+\.\S+$/.test(form.email)) next.email = "Enter a valid email address."; if (form.password.length < 12 || !/[A-Z]/.test(form.password) || !/[a-z]/.test(form.password) || !/\d/.test(form.password) || !/[^A-Za-z0-9]/.test(form.password)) next.password = "Use at least 12 characters with uppercase, lowercase, number, and symbol."; setFormErrors(next); return !Object.keys(next).length; }
  async function submit(event: FormEvent) { event.preventDefault(); if (!organizationId || saving || !validate()) return; setSaving(true); setError(null); setMessage(null); try { const created = await createManagedUser({ organization_id: organizationId, ...form }); if (workspaceId) await assignWorkspaceMember(workspaceId, created.id, workspaceRole); setForm(blankForm); setWorkspaceId(""); setWorkspaceRole("VIEWER"); setFormErrors({}); setMessage(workspaceId ? "User created and workspace access assigned." : "User created securely."); await load(); } catch (cause) { setError(errorMessage(cause)); } finally { setSaving(false); } }
  async function toggle(target: ManagedUser) { setError(null); try { await updateManagedUser(target.id, { is_active: !target.is_active }); setMessage(target.is_active ? "User deactivated." : "User reactivated."); setConfirmTarget(null); await load(); } catch (cause) { setError(errorMessage(cause)); } }
  async function changeRole(target: ManagedUser, role: OrganizationRole) { try { await updateManagedUser(target.id, { role }); setMessage("Organization role updated."); await load(); } catch (cause) { setError(errorMessage(cause)); } }
  async function addMembership() { if (!selected || !addWorkspaceId) return; try { await assignWorkspaceMember(addWorkspaceId, selected.id, addWorkspaceRole); setMessage("Workspace access updated."); setAddWorkspaceId(""); await load(); } catch (cause) { setError(errorMessage(cause)); } }
  async function removeMembership(item: WorkspaceMembership) { try { await deactivateWorkspaceMember(item.workspace_id, item.user_id); setMessage("Workspace access removed."); await load(); } catch (cause) { setError(errorMessage(cause)); } }
  function reset() { setForm(blankForm); setWorkspaceId(""); setWorkspaceRole("VIEWER"); setFormErrors({}); }

  if (!authorized) return <section className="page-shell"><EmptyState title="Access denied" message="You do not have permission to manage organization users." /></section>;
  return <section className="page-shell access-page">
    <div className="access-breadcrumb" aria-label="Breadcrumb"><span>Administration</span><span aria-hidden="true">/</span><strong>Users &amp; Access</strong></div>
    <PageHeader title="Users & Access" description="Manage organization users and their workspace access. Organization roles control global access, while workspace roles control workspace-specific permissions." actions={<PrimaryButton onClick={() => document.getElementById("full-name")?.focus()}>＋ Add User</PrimaryButton>} />
    {error && <Alert>{error}</Alert>}{message && <Alert tone="success">{message}</Alert>}
    <div className="access-layout">
      <Card className="access-form-card" title="＋ Add New User">
        <form className="access-form" onSubmit={submit} noValidate>
          <FormField label="Full name" htmlFor="full-name" required><input id="full-name" className="ui-control" placeholder="Enter full name" value={form.full_name} aria-invalid={!!formErrors.full_name} aria-describedby={formErrors.full_name ? "full-name-error" : undefined} onChange={e => setForm({ ...form, full_name: e.target.value })}/>{formErrors.full_name && <small className="field-error" id="full-name-error">{formErrors.full_name}</small>}</FormField>
          <FormField label="Email" htmlFor="user-email" required><input id="user-email" className="ui-control" type="email" placeholder="Enter email address" autoComplete="off" value={form.email} aria-invalid={!!formErrors.email} aria-describedby={formErrors.email ? "user-email-error" : undefined} onChange={e => setForm({ ...form, email: e.target.value })}/>{formErrors.email && <small className="field-error" id="user-email-error">{formErrors.email}</small>}</FormField>
          <FormField label="Temporary password" htmlFor="temporary-password" required hint="Minimum 12 characters with uppercase, lowercase, number, and symbol."><div className="password-control"><input id="temporary-password" className="ui-control" type={showPassword ? "text" : "password"} placeholder="Enter temporary password" autoComplete="new-password" value={form.password} aria-invalid={!!formErrors.password} aria-describedby="temporary-password-hint temporary-password-error" onChange={e => setForm({ ...form, password: e.target.value })}/><button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword(value => !value)}>{showPassword ? "Hide" : "Show"}</button></div>{formErrors.password && <small className="field-error" id="temporary-password-error">{formErrors.password}</small>}</FormField>
          <FormField label="Organization role" htmlFor="organization-role" required><Select id="organization-role" value={form.role} onChange={e => setForm({ ...form, role: e.target.value as OrganizationRole })}>{roles.map(role => <option key={role} value={role}>{humanize(role)}</option>)}</Select></FormField>
          <FormField label="Initial workspace (optional)" htmlFor="initial-workspace"><Select id="initial-workspace" value={workspaceId} onChange={e => setWorkspaceId(e.target.value)}><option value="">No workspace</option>{workspaces.map(workspace => <option key={workspace.id} value={workspace.id}>{workspace.name}</option>)}</Select></FormField>
          {workspaceId && <FormField label="Workspace role" htmlFor="workspace-role" required><Select id="workspace-role" value={workspaceRole} onChange={e => setWorkspaceRole(e.target.value as WorkspaceRole)}>{workspaceRoles.map(role => <option key={role} value={role}>{humanize(role)}</option>)}</Select></FormField>}
          <div className="access-form-note">ⓘ The temporary password is never displayed after creation.</div><PrimaryButton type="submit" disabled={saving}>{saving ? "Creating user…" : "Create User"}</PrimaryButton><SecondaryButton type="button" disabled={saving} onClick={reset}>Reset Form</SecondaryButton>
        </form>
      </Card>
      <div className="access-content">
        <div className="access-summary-grid"><SummaryCard icon="●" value={users.filter(user => user.is_active).length} label="Active Users" detail="Total active organization users"/><SummaryCard icon="◇" value={roles.length} label="Organization Roles" detail="Available global roles"/><SummaryCard icon="▦" value={workspaces.filter(workspace => workspace.is_active).length} label="Workspaces" detail="Active workspaces"/></div>
        <Card className="access-users-card" title="Organization Users">
          <div className="access-toolbar"><input className="ui-control" aria-label="Search users" placeholder="Search by name, email, or role…" value={search} onChange={e => setSearch(e.target.value)}/><Select aria-label="Filter by organization role" value={roleFilter} onChange={e => setRoleFilter(e.target.value)}><option value="">All roles</option>{roles.map(role => <option key={role} value={role}>{humanize(role)}</option>)}</Select><Select aria-label="Filter by status" value={statusFilter} onChange={e => setStatusFilter(e.target.value)}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></Select><SecondaryButton onClick={() => void load()} aria-label="Refresh users">↻ Refresh</SecondaryButton></div>
          {loading ? <div className="access-loading"><SkeletonLoader lines={5} label="Loading users" /></div> : filtered.length === 0 ? <EmptyState title={users.length ? "No matching users" : "No organization users"} message={users.length ? "Adjust the search or filters and try again." : "Create the first organization user using the form."}/> : <div className="ui-table-wrap"><table className="ui-table access-table"><thead><tr><th>User</th><th>Organization Role</th><th>Workspaces</th><th>Status</th><th><span className="visually-hidden">Actions</span></th></tr></thead><tbody>{filtered.map(user => { const memberRows = membershipFor(user.id); return <tr key={user.id}><td><div className="user-cell"><span className="user-avatar" aria-hidden="true">{initials(user)}</span><div><strong>{user.full_name || "Unnamed user"}</strong><small>{user.email}</small></div></div></td><td>{user.id === actor?.id ? <span className="role-badge">{humanize(user.role)} · You</span> : <Select aria-label={`Organization role for ${user.full_name || user.email}`} value={user.role} onChange={e => void changeRole(user, e.target.value as OrganizationRole)}>{roles.map(role => <option key={role} value={role}>{humanize(role)}</option>)}</Select>}</td><td><strong>{memberRows.length}</strong><button className="link-button" onClick={() => setSelected(user)}>View details</button></td><td><span className="ui-badge" data-tone={user.is_active ? "success" : "danger"}>● {user.is_active ? "Active" : "Inactive"}</span></td><td><details className="action-menu"><summary aria-label={`Actions for ${user.full_name || user.email}`}>•••</summary><div><button onClick={() => setSelected(user)}>Manage Workspace Access</button>{user.id !== actor?.id && <button onClick={() => user.is_active ? setConfirmTarget(user) : void toggle(user)}>{user.is_active ? "Deactivate" : "Reactivate"}</button>}{user.id === actor?.id && <small>Self-deactivation is not permitted.</small>}</div></details></td></tr>; })}</tbody></table></div>}
          {!loading && filtered.length > 0 && <footer className="table-footer">Showing {filtered.length} of {users.length} user{users.length === 1 ? "" : "s"}</footer>}
        </Card>
        <Card className="role-information" title="Role Information"><div><section><span aria-hidden="true">◇</span><div><h4>Organization Roles</h4><p>Control what users can do across the organization. Examples: Organization Admin, Developer, Read Only.</p></div></section><section><span aria-hidden="true">▦</span><div><h4>Workspace Roles</h4><p>Control access inside a specific workspace. Examples: Owner, Admin, DBA, Developer, Viewer.</p></div></section></div></Card>
      </div>
    </div>
    {confirmTarget && <AccessDialog title={`${confirmTarget.is_active ? "Deactivate" : "Reactivate"} user`} onClose={() => setConfirmTarget(null)}><p>{confirmTarget.is_active ? "This user will be unable to sign in. Existing audit history will be retained." : "This user will regain access according to their assigned roles."}</p><div className="modal-actions"><SecondaryButton onClick={() => setConfirmTarget(null)}>Cancel</SecondaryButton><PrimaryButton onClick={() => void toggle(confirmTarget)}>Confirm {confirmTarget.is_active ? "deactivation" : "reactivation"}</PrimaryButton></div></AccessDialog>}
    {selected && <AccessDialog title={`Workspace access · ${selected.full_name || selected.email}`} onClose={() => setSelected(null)}><p className="modal-intro">Organization role: <strong>{humanize(selected.role)}</strong>. Workspace assignments are managed independently below.</p><div className="membership-list">{membershipFor(selected.id).length ? membershipFor(selected.id).map(item => { const workspace = workspaces.find(row => row.id === item.workspace_id); return <div key={item.id}><div><strong>{workspace?.name || "Unknown workspace"}</strong><span className="ui-badge">{humanize(item.role)}</span></div><SecondaryButton onClick={() => void removeMembership(item)}>Remove access</SecondaryButton></div>; }) : <EmptyState title="No workspace access" message="This user has no active workspace memberships."/>}</div><div className="membership-add"><Select aria-label="Workspace to add" value={addWorkspaceId} onChange={e => setAddWorkspaceId(e.target.value)}><option value="">Select workspace</option>{workspaces.filter(workspace => !membershipFor(selected.id).some(item => item.workspace_id === workspace.id)).map(workspace => <option key={workspace.id} value={workspace.id}>{workspace.name}</option>)}</Select><Select aria-label="Workspace role to assign" value={addWorkspaceRole} onChange={e => setAddWorkspaceRole(e.target.value as WorkspaceRole)}>{workspaceRoles.map(role => <option key={role}>{humanize(role)}</option>)}</Select><PrimaryButton disabled={!addWorkspaceId} onClick={() => void addMembership()}>Add access</PrimaryButton></div></AccessDialog>}
  </section>;
}
