import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { UsersAccessPage } from "./UsersAccessPage";
import { AuthContext, type AuthState } from "../../stores/auth-store";

const listUsers = vi.fn(), createUser = vi.fn(), updateUser = vi.fn(), listMembers = vi.fn(), assignMember = vi.fn(), deactivateMember = vi.fn(), listWorkspaces = vi.fn();
vi.mock("../../api/access-api", () => ({ listManagedUsers: (...args: unknown[]) => listUsers(...args), createManagedUser: (...args: unknown[]) => createUser(...args), updateManagedUser: (...args: unknown[]) => updateUser(...args), listWorkspaceMembers: (...args: unknown[]) => listMembers(...args), assignWorkspaceMember: (...args: unknown[]) => assignMember(...args), deactivateWorkspaceMember: (...args: unknown[]) => deactivateMember(...args) }));
vi.mock("../../api/workspace-api", () => ({ listWorkspaces: (...args: unknown[]) => listWorkspaces(...args) }));
const admin = { organizationId: "O", user: { id: "A", organization_id: "O", email: "admin@example.com", full_name: "Admin User", role: "organization_admin", is_active: true }, session: null, isAuthenticated: true, isInitializing: false, login: vi.fn(), logout: vi.fn() } satisfies AuthState;
const users = [admin.user!, { id: "U", organization_id: "O", email: "dev@example.com", full_name: "Dev Person", role: "developer", is_active: false }];
const workspace = { id: "W", organization_id: "O", name: "ERP", slug: "erp", is_active: true };
const membership = { id: "M", organization_id: "O", workspace_id: "W", user_id: "U", role: "VIEWER", is_active: true };
function page(auth = admin) { return render(<AuthContext.Provider value={auth}><UsersAccessPage /></AuthContext.Provider>); }

describe("UsersAccessPage", () => {
  beforeEach(() => { vi.clearAllMocks(); listUsers.mockResolvedValue(users); listWorkspaces.mockResolvedValue([workspace]); listMembers.mockResolvedValue([membership]); createUser.mockResolvedValue({ ...users[1], id: "N" }); updateUser.mockResolvedValue({}); assignMember.mockResolvedValue({}); deactivateMember.mockResolvedValue(undefined); });
  it("renders live summaries and organization users for an administrator", async () => { page(); expect(await screen.findByText("Dev Person")).toBeInTheDocument(); expect(screen.getByText("Active Users").closest("section")).toHaveTextContent("1"); expect(screen.getAllByText("Workspaces")[0].closest("section")).toHaveTextContent("1"); expect(screen.queryByText("Pending Invitations")).not.toBeInTheDocument(); });
  it("denies unauthorized users without loading management data", () => { page({ ...admin, user: { ...admin.user!, role: "read_only_user" } }); expect(screen.getByText("Access denied")).toBeInTheDocument(); expect(listUsers).not.toHaveBeenCalled(); });
  it("shows an accessible loading skeleton", () => { listUsers.mockReturnValue(new Promise(() => undefined)); page(); expect(screen.getByRole("status", { name: "Loading users" })).toBeInTheDocument(); });
  it("filters by name, email, role, and status", async () => { page(); await screen.findByText("Dev Person"); const search = screen.getByLabelText("Search users"); fireEvent.change(search, { target: { value: "admin" } }); expect(screen.queryByText("Dev Person")).not.toBeInTheDocument(); fireEvent.change(search, { target: { value: "dev@example" } }); expect(screen.getByText("Dev Person")).toBeInTheDocument(); fireEvent.change(search, { target: { value: "developer" } }); expect(screen.getByText("Dev Person")).toBeInTheDocument(); fireEvent.change(search, { target: { value: "" } }); fireEvent.change(screen.getByLabelText("Filter by status"), { target: { value: "true" } }); expect(screen.queryByText("Dev Person")).not.toBeInTheDocument(); fireEvent.change(screen.getByLabelText("Filter by organization role"), { target: { value: "developer" } }); fireEvent.change(screen.getByLabelText("Filter by status"), { target: { value: "" } }); expect(screen.getByText("Dev Person")).toBeInTheDocument(); });
  it("shows workspace role only when a workspace is selected", async () => { page(); await screen.findByText("Dev Person"); expect(screen.queryByLabelText(/Workspace role/i)).not.toBeInTheDocument(); fireEvent.change(screen.getByLabelText(/Initial workspace/i), { target: { value: "W" } }); expect(await screen.findByLabelText(/Workspace role/i)).toBeInTheDocument(); });
  it("provides linked validation and preserves values after API failure", async () => { createUser.mockRejectedValue(new Error("Duplicate user")); page(); await screen.findByText("Dev Person"); fireEvent.click(screen.getByRole("button", { name: "Create User" })); expect(screen.getByText("Full name is required.")).toHaveAttribute("id", "full-name-error"); fireEvent.change(screen.getByLabelText("Full name *"), { target: { value: "New Person" } }); fireEvent.change(screen.getByLabelText("Email *"), { target: { value: "new@example.com" } }); fireEvent.change(screen.getByLabelText("Temporary password *"), { target: { value: "SecurePass123!" } }); fireEvent.click(screen.getByRole("button", { name: "Create User" })); expect(await screen.findByRole("alert")).toHaveTextContent("Duplicate user"); expect(screen.getByLabelText("Full name *")).toHaveValue("New Person"); });
  it("creates once, refreshes data, and never renders the submitted password", async () => { let resolve!: (value: unknown) => void; createUser.mockReturnValue(new Promise(value => { resolve = value; })); page(); await screen.findByText("Dev Person"); fireEvent.change(screen.getByLabelText("Full name *"), { target: { value: "New Person" } }); fireEvent.change(screen.getByLabelText("Email *"), { target: { value: "new@example.com" } }); fireEvent.change(screen.getByLabelText("Temporary password *"), { target: { value: "SecurePass123!" } }); const button = screen.getByRole("button", { name: "Create User" }); fireEvent.click(button); fireEvent.click(button); expect(createUser).toHaveBeenCalledTimes(1); resolve({ ...users[1], id: "N" }); await waitFor(() => expect(listUsers).toHaveBeenCalledTimes(2)); expect(screen.queryByDisplayValue("SecurePass123!")).not.toBeInTheDocument(); });
  it("loads real memberships and requires confirmation before deactivation", async () => { listUsers.mockResolvedValue([users[0], { ...users[1], is_active: true }]); page(); await screen.findByText("Dev Person"); fireEvent.click(screen.getAllByRole("button", { name: "View details" })[0]); expect(screen.getByRole("dialog")).toHaveTextContent("ERP"); expect(screen.getByRole("dialog")).toHaveTextContent("Viewer"); fireEvent.click(screen.getByLabelText("Close dialog")); fireEvent.click(screen.getByLabelText("Actions for Dev Person")); fireEvent.click(screen.getByRole("button", { name: "Deactivate" })); expect(updateUser).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole("button", { name: "Confirm deactivation" })); await waitFor(() => expect(updateUser).toHaveBeenCalledWith("U", { is_active: false })); });
});
