import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { assignWorkspaceMember, createManagedUser, listManagedUsers, updateManagedUser } from "../../api/access-api";
import { listWorkspaces } from "../../api/workspace-api";
import { useAuth } from "../../hooks/use-auth";
import type { ManagedUser, OrganizationRole, WorkspaceRole } from "../../models/access";
import type { Workspace } from "../../models/workspace";

const roles: OrganizationRole[] = ["organization_admin", "developer", "dba", "support_engineer", "read_only_user", "auditor"];
const errorMessage = (value: unknown) => value instanceof Error ? value.message : "The access request failed.";

export function UsersAccessPage() {
  const { organizationId, user: actor } = useAuth();
  const authorized = actor?.role === "super_admin" || actor?.role === "organization_admin";
  const [users, setUsers] = useState<ManagedUser[]>([]); const [workspaces, setWorkspaces] = useState<Workspace[]>([]);
  const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  const [form, setForm] = useState({ full_name: "", email: "", password: "", role: "read_only_user" as OrganizationRole });
  const [workspaceId, setWorkspaceId] = useState(""); const [workspaceRole, setWorkspaceRole] = useState<WorkspaceRole>("VIEWER");
  const load = useCallback(async (signal?: AbortSignal) => { if (!organizationId || !authorized) { setLoading(false); return; } setLoading(true); setError(null); try { const [u, w] = await Promise.all([listManagedUsers(organizationId, signal), listWorkspaces(organizationId, signal)]); setUsers(u); setWorkspaces(w); } catch (e) { if ((e as {name?: string}).name !== "AbortError") setError(errorMessage(e)); } finally { setLoading(false); } }, [organizationId, authorized]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  const filtered = useMemo(() => users.filter((u) => `${u.full_name} ${u.email} ${u.role}`.toLowerCase().includes(search.toLowerCase())), [users, search]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!organizationId || saving) return; setSaving(true); setError(null); setMessage(null); try { const created = await createManagedUser({ organization_id: organizationId, ...form }); if (workspaceId) await assignWorkspaceMember(workspaceId, created.id, workspaceRole); setForm({ full_name: "", email: "", password: "", role: "read_only_user" }); setWorkspaceId(""); setMessage(workspaceId ? "User created and workspace access assigned." : "User created securely."); await load(); } catch (e) { setError(errorMessage(e)); } finally { setSaving(false); } }
  async function toggle(target: ManagedUser) { if (target.id === actor?.id) return; setError(null); try { await updateManagedUser(target.id, { is_active: !target.is_active }); setMessage(target.is_active ? "User deactivated." : "User reactivated."); await load(); } catch (e) { setError(errorMessage(e)); } }
  if (!authorized) return <section className="page-shell"><div className="empty-state" role="alert"><h1>Access denied</h1><p>You do not have permission to manage organization users.</p></div></section>;
  return <section className="page-shell access-page"><header className="page-header"><div><p className="eyebrow">Administration</p><h1>Users &amp; Access</h1><p>Create organization identities and manage account status. Workspace roles remain separate from organization roles.</p></div><span className="status-chip">{users.filter(u=>u.is_active).length} active</span></header>
    {error && <div className="alert error" role="alert">{error}</div>}{message && <div className="alert success" role="status">{message}</div>}
    <div className="access-grid"><form className="panel access-form" onSubmit={submit}><h2>Add user</h2><label>Full name<input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>Email<input required type="email" autoComplete="off" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Temporary password<input required minLength={12} type="password" autoComplete="new-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><small>At least 12 characters with upper/lowercase, number, and symbol.</small></label><label>Organization role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value as OrganizationRole})}>{roles.map(r=><option key={r} value={r}>{r.replaceAll("_"," ")}</option>)}</select></label><label>Initial workspace (optional)<select value={workspaceId} onChange={e=>setWorkspaceId(e.target.value)}><option value="">No workspace</option>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>{workspaceId && <label>Workspace role<select value={workspaceRole} onChange={e=>setWorkspaceRole(e.target.value as WorkspaceRole)}>{(["OWNER","ADMIN","DBA","DEVELOPER","VIEWER","AUDITOR"] as WorkspaceRole[]).map(r=><option key={r}>{r}</option>)}</select></label>}<button className="primary-button" disabled={saving}>{saving ? "Creating…" : "Create user"}</button></form>
      <div className="panel"><div className="section-heading"><div><h2>Organization users</h2><p>{workspaces.length} workspace{workspaces.length===1?"":"s"} available</p></div><input aria-label="Search users" placeholder="Search name, email, or role" value={search} onChange={e=>setSearch(e.target.value)}/></div>{loading ? <p role="status">Loading users…</p> : filtered.length===0 ? <div className="empty-state"><h3>No users found</h3><p>{search ? "Try a different search." : "Create the first organization user."}</p></div> : <div className="table-wrap"><table><thead><tr><th>User</th><th>Organization role</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map(u=><tr key={u.id}><td><strong>{u.full_name || "Unnamed user"}</strong><br/><small>{u.email}</small></td><td>{u.role.replaceAll("_"," ")}</td><td><span className={`status-chip ${u.is_active?"":"muted"}`}>{u.is_active?"Active":"Inactive"}</span></td><td><button className="secondary-button" disabled={u.id===actor?.id} title={u.id===actor?.id?"You cannot deactivate your own account":undefined} onClick={()=>void toggle(u)}>{u.is_active?"Deactivate":"Reactivate"}</button></td></tr>)}</tbody></table></div>}</div></div></section>;
}
