import { fireEvent,render,screen,waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { beforeEach,describe,expect,it,vi } from "vitest";
import { AuthContext,type AuthState } from "../../stores/auth-store";
import { LearningPage } from "./LearningPage";

const workspaces=vi.fn(),dashboard=vi.fn(),history=vi.fn(),feedback=vi.fn(),knowledge=vi.fn(),review=vi.fn(),submit=vi.fn();
vi.mock("../../api/workspace-api",()=>({listWorkspaces:(...a:unknown[])=>workspaces(...a)}));
vi.mock("../../api/learning-api",()=>({loadLearningDashboard:(...a:unknown[])=>dashboard(...a),listKnowledge:(...a:unknown[])=>knowledge(...a)}));
vi.mock("../../api/investigation-api",()=>({loadInvestigationHistory:(...a:unknown[])=>history(...a)}));
vi.mock("../../api/feedback-api",()=>({listFeedback:(...a:unknown[])=>feedback(...a),reviewFeedback:(...a:unknown[])=>review(...a),submitInvestigationFeedback:(...a:unknown[])=>submit(...a)}));
const auth={organizationId:"O",user:{id:"U",organization_id:"O",email:"admin@example.com",full_name:"Admin",role:"organization_admin",is_active:true},session:null,isAuthenticated:true,isInitializing:false,login:vi.fn(),logout:vi.fn()} satisfies AuthState;
const investigation={id:"I",organization_id:"O",workspace_id:"W",connection_id:"C",connection_name:"DB",user_question:"Why did payroll fail?",detected_intent:"MISSING_DATA",ai_answer:"## Root Cause Analysis\nDOB was missing. Evidence SQL-1 and PROC-1.\n## Recommendation\nValidate dates.\n## Missing Information / Clarifying Questions\nNone.",confidence_score:.72,report_path:"",status:"AI_ANSWERED",created_at:"2026-01-01"};
const pending={id:"F",organization_id:"O",workspace_id:"W",investigation_id:"I",rating:"WRONG_ROOT_CAUSE",actual_root_cause:"DOB null handling was absent",actual_fix_applied:"Added a null guard",sql_or_procedure_changed:"calculate_age",test_cases_executed:"Null DOB regression",proof_of_fix:"Regression passed",rollback_used:"Rollback script prepared",production_issue_resolved:true,notes:"Verified in staging",status:"PENDING_APPROVAL",review_notes:"",created_at:"2026-07-13T10:00:00Z"};
function page(value:AuthState=auth){return render(<AuthContext.Provider value={value}><MemoryRouter><LearningPage/></MemoryRouter></AuthContext.Provider>);}

describe("LearningPage",()=>{
  beforeEach(()=>{vi.clearAllMocks();workspaces.mockResolvedValue([{id:"W",name:"Main",organization_id:"O",slug:"main",is_active:true}]);dashboard.mockResolvedValue({open_investigations:1,pending_feedback:1,pending_approval:1,approved_knowledge:1,reminders:[]});history.mockResolvedValue([investigation]);feedback.mockResolvedValue([pending]);knowledge.mockResolvedValue([{id:"K",title:"Approved fix",actual_root_cause:"Retry"}]);review.mockResolvedValue({});submit.mockResolvedValue(pending);});
  it("shows five open or AI-answered investigations and an empty review queue",async()=>{const rows=Array.from({length:5},(_,index)=>({...investigation,id:`I-${index+1}`,user_question:`Issue ${index+1}`,status:index%2?"OPEN":"AI_ANSWERED"}));history.mockResolvedValue(rows);feedback.mockResolvedValue([]);dashboard.mockResolvedValue({open_investigations:5,pending_feedback:0,pending_approval:0,approved_knowledge:0,reminders:[]});page();expect(await screen.findAllByRole("button",{name:"Provide Feedback"})).toHaveLength(5);expect(screen.getByText("No feedback to review")).toBeInTheDocument();expect(screen.getByText("5 awaiting feedback")).toBeInTheDocument();});
  it("submits feedback then refreshes counters, awaiting records, and review queue",async()=>{history.mockResolvedValueOnce([investigation]).mockResolvedValueOnce([{...investigation,status:"DEVELOPER_REVIEW"}]);feedback.mockResolvedValueOnce([]).mockResolvedValueOnce([pending]);dashboard.mockResolvedValueOnce({open_investigations:1,pending_feedback:0,pending_approval:0,approved_knowledge:0,reminders:[]}).mockResolvedValueOnce({open_investigations:0,pending_feedback:1,pending_approval:1,approved_knowledge:0,reminders:[]});page();fireEvent.click(await screen.findByRole("button",{name:"Provide Feedback"}));fireEvent.change(screen.getByLabelText("Actual root cause"),{target:{value:"Verified cause"}});fireEvent.click(screen.getByRole("button",{name:"Submit for DBA/Lead Approval"}));expect(await screen.findByText(/Dashboard counters and review queue have been refreshed/)).toBeInTheDocument();expect(screen.getByText("No investigations awaiting feedback")).toBeInTheDocument();expect(screen.getByText("Reviewer Correction")).toBeInTheDocument();expect(screen.getByText("Pending feedback").parentElement).toHaveTextContent("1");expect(screen.getByText("Pending approval").parentElement).toHaveTextContent("1");});
  it("restores the submitted state correctly on a fresh page load",async()=>{history.mockResolvedValue([{...investigation,status:"DEVELOPER_REVIEW"}]);feedback.mockResolvedValue([pending]);dashboard.mockResolvedValue({open_investigations:0,pending_feedback:1,pending_approval:1,approved_knowledge:0,reminders:[]});page();expect(await screen.findByText("No investigations awaiting feedback")).toBeInTheDocument();expect(screen.getByText("Reviewer Correction")).toBeInTheDocument();expect(screen.queryByRole("button",{name:"Provide Feedback"})).not.toBeInTheDocument();});
  it("does not offer submission controls to a role without feedback permission",async()=>{page({...auth,user:{...auth.user!,role:"read_only_user"}});expect(await screen.findByText("Feedback submission permission required")).toBeInTheDocument();expect(screen.queryByRole("button",{name:"Provide Feedback"})).not.toBeInTheDocument();});
  it("shows loading then a pending AI-versus-correction workspace with evidence",async()=>{dashboard.mockImplementation(()=>new Promise((resolve)=>setTimeout(()=>resolve({open_investigations:1,pending_feedback:1,pending_approval:1,approved_knowledge:1,reminders:[]}),20)));page();expect(screen.getByRole("status",{name:"Loading feedback review"})).toBeInTheDocument();expect(await screen.findByText("AI Investigation Result")).toBeInTheDocument();expect(screen.getByText("Reviewer Correction")).toBeInTheDocument();expect(screen.getAllByText("SQL-1").length).toBeGreaterThan(0);fireEvent.click(screen.getAllByText("View details")[1]);expect(screen.getAllByText(/DOB was missing/).length).toBeGreaterThan(0);});
  it.each([["APPROVED_KNOWLEDGE","Approved Knowledge"],["REJECTED","Rejected"]])("renders completed %s feedback",async(status,label)=>{feedback.mockResolvedValue([{...pending,status}]);page();expect(await screen.findAllByText(label)).not.toHaveLength(0);expect(screen.getByRole("button",{name:"Approve as Knowledge"})).toBeDisabled();});
  it("confirms approval with the supported API payload",async()=>{page();fireEvent.click(await screen.findByRole("button",{name:"Approve as Knowledge"}));expect(screen.getByRole("dialog")).toHaveTextContent("Live database evidence remains authoritative");fireEvent.change(screen.getByLabelText("Review notes"),{target:{value:"Evidence checked"}});fireEvent.click(screen.getByRole("button",{name:"Confirm approval"}));await waitFor(()=>expect(review).toHaveBeenCalledWith("F",expect.objectContaining({approved:true,review_notes:"Evidence checked",confidence_after_approval:.95,severity:"medium"})));expect(await screen.findByText(/approved as workspace knowledge/i)).toBeInTheDocument();});
  it("requires a rejection reason and submits it",async()=>{page();fireEvent.click(await screen.findByRole("button",{name:"Reject Feedback"}));fireEvent.click(screen.getByRole("button",{name:"Confirm rejection"}));expect(screen.getByRole("alert")).toHaveTextContent("required");fireEvent.change(screen.getByLabelText(/Rejection reason/),{target:{value:"Correction is unsupported"}});fireEvent.click(screen.getByRole("button",{name:"Confirm rejection"}));await waitFor(()=>expect(review).toHaveBeenCalledWith("F",expect.objectContaining({approved:false,review_notes:"Correction is unsupported"})));});
  it("shows load failures",async()=>{dashboard.mockRejectedValueOnce(new Error("Learning denied"));page();expect(await screen.findByRole("alert")).toHaveTextContent("Learning denied");});
  it("shows review API failures",async()=>{review.mockRejectedValue(new Error("Review failed"));page();fireEvent.click(await screen.findByRole("button",{name:"Approve as Knowledge"}));fireEvent.click(screen.getByRole("button",{name:"Confirm approval"}));expect(await screen.findByRole("alert")).toHaveTextContent("Review failed");});
});
