import { fireEvent,render,screen,waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { beforeEach,describe,expect,it,vi } from "vitest";
import { AuthContext,type AuthState } from "../../stores/auth-store";
import { LearningPage } from "./LearningPage";

const workspaces=vi.fn(),dashboard=vi.fn(),history=vi.fn(),feedback=vi.fn(),knowledge=vi.fn(),review=vi.fn();
vi.mock("../../api/workspace-api",()=>({listWorkspaces:(...a:unknown[])=>workspaces(...a)}));
vi.mock("../../api/learning-api",()=>({loadLearningDashboard:(...a:unknown[])=>dashboard(...a),listKnowledge:(...a:unknown[])=>knowledge(...a)}));
vi.mock("../../api/investigation-api",()=>({loadInvestigationHistory:(...a:unknown[])=>history(...a)}));
vi.mock("../../api/feedback-api",()=>({listFeedback:(...a:unknown[])=>feedback(...a),reviewFeedback:(...a:unknown[])=>review(...a)}));
const auth={organizationId:"O",user:null,session:null,isAuthenticated:true,isInitializing:false,login:vi.fn(),logout:vi.fn()} satisfies AuthState;
const investigation={id:"I",organization_id:"O",workspace_id:"W",connection_id:"C",connection_name:"DB",user_question:"Why did payroll fail?",detected_intent:"MISSING_DATA",ai_answer:"## Root Cause Analysis\nDOB was missing. Evidence SQL-1 and PROC-1.\n## Recommendation\nValidate dates.\n## Missing Information / Clarifying Questions\nNone.",confidence_score:.72,report_path:"",status:"AI_ANSWERED",created_at:"2026-01-01"};
const pending={id:"F",organization_id:"O",workspace_id:"W",investigation_id:"I",rating:"WRONG_ROOT_CAUSE",actual_root_cause:"DOB null handling was absent",actual_fix_applied:"Added a null guard",sql_or_procedure_changed:"calculate_age",test_cases_executed:"Null DOB regression",proof_of_fix:"Regression passed",rollback_used:"Rollback script prepared",production_issue_resolved:true,notes:"Verified in staging",status:"PENDING_APPROVAL",review_notes:"",created_at:"2026-07-13T10:00:00Z"};
function page(){return render(<AuthContext.Provider value={auth}><MemoryRouter><LearningPage/></MemoryRouter></AuthContext.Provider>);}

describe("LearningPage",()=>{
  beforeEach(()=>{vi.clearAllMocks();workspaces.mockResolvedValue([{id:"W",name:"Main",organization_id:"O",slug:"main",is_active:true}]);dashboard.mockResolvedValue({open_investigations:1,pending_feedback:1,pending_approval:1,approved_knowledge:1,reminders:[]});history.mockResolvedValue([investigation]);feedback.mockResolvedValue([pending]);knowledge.mockResolvedValue([{id:"K",title:"Approved fix",actual_root_cause:"Retry"}]);review.mockResolvedValue({});});
  it("shows loading then a pending AI-versus-correction workspace with evidence",async()=>{dashboard.mockImplementation(()=>new Promise((resolve)=>setTimeout(()=>resolve({open_investigations:1,pending_feedback:1,pending_approval:1,approved_knowledge:1,reminders:[]}),20)));page();expect(screen.getByRole("status",{name:"Loading feedback review"})).toBeInTheDocument();expect(await screen.findByText("AI Investigation Result")).toBeInTheDocument();expect(screen.getByText("Reviewer Correction")).toBeInTheDocument();expect(screen.getAllByText("SQL-1").length).toBeGreaterThan(0);fireEvent.click(screen.getAllByText("View details")[1]);expect(screen.getAllByText(/DOB was missing/).length).toBeGreaterThan(0);});
  it.each([["APPROVED_KNOWLEDGE","Approved Knowledge"],["REJECTED","Rejected"]])("renders completed %s feedback",async(status,label)=>{feedback.mockResolvedValue([{...pending,status}]);page();expect(await screen.findAllByText(label)).not.toHaveLength(0);expect(screen.getByRole("button",{name:"Approve as Knowledge"})).toBeDisabled();});
  it("confirms approval with the supported API payload",async()=>{page();fireEvent.click(await screen.findByRole("button",{name:"Approve as Knowledge"}));expect(screen.getByRole("dialog")).toHaveTextContent("Live database evidence remains authoritative");fireEvent.change(screen.getByLabelText("Review notes"),{target:{value:"Evidence checked"}});fireEvent.click(screen.getByRole("button",{name:"Confirm approval"}));await waitFor(()=>expect(review).toHaveBeenCalledWith("F",expect.objectContaining({approved:true,review_notes:"Evidence checked",confidence_after_approval:.95,severity:"medium"})));expect(await screen.findByText(/approved as workspace knowledge/i)).toBeInTheDocument();});
  it("requires a rejection reason and submits it",async()=>{page();fireEvent.click(await screen.findByRole("button",{name:"Reject Feedback"}));fireEvent.click(screen.getByRole("button",{name:"Confirm rejection"}));expect(screen.getByRole("alert")).toHaveTextContent("required");fireEvent.change(screen.getByLabelText(/Rejection reason/),{target:{value:"Correction is unsupported"}});fireEvent.click(screen.getByRole("button",{name:"Confirm rejection"}));await waitFor(()=>expect(review).toHaveBeenCalledWith("F",expect.objectContaining({approved:false,review_notes:"Correction is unsupported"})));});
  it("shows load failures",async()=>{dashboard.mockRejectedValueOnce(new Error("Learning denied"));page();expect(await screen.findByRole("alert")).toHaveTextContent("Learning denied");});
  it("shows review API failures",async()=>{review.mockRejectedValue(new Error("Review failed"));page();fireEvent.click(await screen.findByRole("button",{name:"Approve as Knowledge"}));fireEvent.click(screen.getByRole("button",{name:"Confirm approval"}));expect(await screen.findByRole("alert")).toHaveTextContent("Review failed");});
});
