import { useState, type FormEvent } from "react";
import { submitInvestigationFeedback } from "../../api/feedback-api";
import type { FeedbackRating } from "../../models/feedback";
const ratings: FeedbackRating[] = ["HELPFUL", "NOT_HELPFUL", "PARTIALLY_CORRECT", "WRONG_ROOT_CAUSE", "MISSING_EVIDENCE", "NEEDS_DBA_REVIEW"];
export function FeedbackPanel({ investigationId }: { investigationId: string | null | undefined }) {
  const [rating, setRating] = useState<FeedbackRating>("HELPFUL"); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  if (!investigationId) return null;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form=event.currentTarget; const data=new FormData(form); const production=data.get("production_issue_resolved"); setError(null); try { await submitInvestigationFeedback(investigationId!, { rating, actual_root_cause:String(data.get("actual_root_cause")||"").trim(), actual_fix_applied:String(data.get("actual_fix_applied")||"").trim(), sql_or_procedure_changed:String(data.get("sql_or_procedure_changed")||"").trim(), test_cases_executed:String(data.get("test_cases_executed")||"").trim(), proof_of_fix:String(data.get("proof_of_fix")||"").trim(), rollback_used:String(data.get("rollback_used")||"").trim(), production_issue_resolved:production === "" ? null : production === "true", notes:String(data.get("notes")||"").trim() }); form.reset(); setMessage("Feedback submitted. Status is Pending Approval."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Feedback submission failed."); } }
  return <section aria-labelledby="feedback-title"><h3 id="feedback-title">Developer feedback</h3><div>{ratings.map((item) => <button type="button" aria-pressed={rating===item} onClick={() => setRating(item)} key={item}>{item.replaceAll("_", " ")}</button>)}</div>
    <form onSubmit={(e) => void submit(e)}><label>Actual root cause<textarea name="actual_root_cause" /></label><label>Actual fix applied<textarea name="actual_fix_applied" /></label><label>SQL/procedure changed<textarea name="sql_or_procedure_changed" /></label><label>Test cases executed<textarea name="test_cases_executed" /></label><label>Proof of fix<textarea name="proof_of_fix" /></label><label>Rollback used?<input name="rollback_used" /></label><label>Production issue resolved?<select name="production_issue_resolved"><option value="">Unknown</option><option value="true">Yes</option><option value="false">No</option></select></label><label>Notes<textarea name="notes" /></label><button type="submit">Submit for DBA/Lead Approval</button></form>
    {message ? <p role="status">{message}</p> : null}{error ? <div role="alert">{error}</div> : null}</section>;
}
